### ISSUE TITLE
Listenable values get buffered

### ISSUE THREAD

**Issue by Andarist** [krawaller/callbag-sample-combine#1] opened 2018-04-30 10:38 UTC
IMHO it is unintended side-effect of the current implementation, but if pullable source does not respond back immediately then listenable values (in `origVals`) stay buffered and will be emitted later when finally pullable source respond back with a value.

This results in emitted values having stale (buffered ones) values.

**Comment by krawaller** [comment] 2018-04-30 10:45
Unless I'm misunderstanding you, that is the intended behaviour - you get the listenable values in the order they're emitted.

What would a failing test look like that captures the scenario you describe?

**Comment by krawaller** [comment] 2018-04-30 10:50
Perhaps what you actually need is a combination of [callbag-latest](https://github.com/krawaller/callbag-latest) and [callbag-sample](https://github.com/staltz/callbag-sample), as in [the example here](https://github.com/krawaller/callbag-latest)?

**Comment by Andarist** [comment] 2018-04-30 12:05
Actually I'm working on a `withLatestFrom` operator and thought I could just compose `sampleCombine` + `latest` as suggested by Andre in [his article](https://egghead.io/articles/comparing-callbags-to-rxjs-for-reactive-programming) instead of providing a completely custom implementation.

If the buffering thing is expected behaviour of `sampleCombine` you can close this issue and I will just go with custom implementation for `withLatestFrom` - I just have been studying your source code and thought that this might not be intended behaviour, so I thought I'd raise a concern about it.

**Comment by krawaller** [comment] 2018-04-30 13:07
Hmm. Thinking some more about it, it isn't immediately obvious (to me) what behaviour is actually preferable in the scenario you describe. Intuitively I think the existing behaviour is better, but I'm not sure.

But - I do want this operator to behave the same as [callbag-sample](https://github.com/staltz/callbag-sample). Even if there's no literal dependency, I want to be able to say that they function in the same way.

I'm going to close this issue for now, but I suggest you post the same issue at [callbag-sample](https://github.com/staltz/callbag-sample). Should that change behaviour, I'll make `callbag-sample-combine` follow suite!

**Closed as completed by krawaller** 2018-04-30 13:07 UTC

**Comment by krawaller** [comment] 2018-04-30 13:12
Another thought - couldn't `withLatestFrom` be built by combining [callbag-combine](https://github.com/staltz/callbag-combine) and [callbag-latest](https://github.com/krawaller/callbag-latest)?

**Comment by Andarist** [comment] 2018-04-30 14:10
> I'm going to close this issue for now, but I suggest you post the same issue at callbag-sample. Should that change behaviour, I'll make callbag-sample-combine follow suite!

Not sure how to relate to `callbag-sample` here because it just passes pulled value to the sink so it just doesn't have to decide how to handle received value from the listenable source.

> Another thought - couldn't withLatestFrom be built by combining callbag-combine and callbag-latest?

Maybe, but not at the moment as `callbag-combine` does not work with pullable source (even though it claims to).

**Comment by krawaller** [comment] 2018-04-30 14:17
> Not sure how to relate to callbag-sample here because it just passes pulled value to the sink so it just doesn't have to decide how to handle received value from the listenable source.

Don't it? They are both operators to sample from `A` whenever `B` emits. The *only* difference between `callbag-sample` and `callbag-sample-combine` is that the former will just pass on the sampled data from `A`, while the latter will also attach the emission from `B` that caused the sampling.

But maybe I'm misunderstanding something?

**Comment by Andarist** [comment] 2018-04-30 14:43
Your description is correct, but the "problem" here (in `callbag-sample-combine`) comes from the fact that there is no direct connection between data request and data response from a pullable source. 

In case of `callbag-sample` this fact doesn't matter because it doesn't pair those listenable and pullable values, it just sends a request and pass on whatever got received later. 

You are right though that in case of both those operators there are equal numbers of data requests and data points received (if we consider infinite timeline).

Considering other possible behaviour - parity between requests and data points would still be there in the sense of their count, but not necessarily in what data points would be passed on.

I guess there is no good answer here, but when I think about it `withLatestFrom` has to be implemented from scratch anyway, because I want to be sure in the sink that both received values are latest at this point in time and when relaying on a pullable source I lose that certainty.

**Comment by krawaller** [comment] 2018-04-30 15:27
Hmm. The behaviour you want, is that to always use the latest value from the listenable when the pullable emits?

I’m starting to wonder if maybe it’d be worth adding a flag that uses that behaviour instead.

**Comment by Andarist** [comment] 2018-04-30 16:20
> Hmm. The behaviour you want, is that to always use the latest value from the listenable when the pullable emits?

I actually don't really care that much about pullable sources, just thought it would be neat to reuse existing operators with the help of `latest` converter, but at the moment it feels like it brings more questions than answers. So I'm kinda torn on this one.

My true goal is to create `withLatestFrom` that would emit on A with addition of latest B, converting B from listenable to pullable was only one idea how this could be achieved, merely an implementation detail. User facing inputs should be 2 listenables.

I kinda wish there was a way to distinguish pullable callbags from listenables ones so operators could provide appropriate implementations based on that, but 🤷‍♂️ 

> I’m starting to wonder if maybe it’d be worth adding a flag that uses that behaviour instead.

Personally I would advocate for creating a separate operator, not sure though which version should stay as `sampleCombine` and which one should get a new name.

**Comment by krawaller** [comment] 2018-05-01 05:53
> Personally I would advocate for creating a separate operator

Yeah, you're probably right. Better to make a separate `callbag-sample-latest-combine`, and keep the individual operators simple.

> In case of callbag-sample this fact doesn't matter because it doesn't pair those listenable and pullable values, it just sends a request and pass on whatever got received later.

But, surely this *does* apply to `callbag-sample` too, even though it doesn't pair the values? We're talking about whether to use the latest value or whether to emit in the same order as from the listenable. In other words, we could make a new `callbag-sample-latest`.

**Comment by Andarist** [comment] 2018-05-04 13:40
> But, surely this does apply to callbag-sample too, even though it doesn't pair the values? We're talking about whether to use the latest value or whether to emit in the same order as from the listenable. In other words, we could make a new callbag-sample-latest.

I guess you are right, same rule indeed apply to the `callbag-sample` - each received data from the listenable pairs to the pulled value, new listenable data doesn't cancel "pending" pull.
